### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MasterOfTheTiger** [snori74/twenty#1]
Hello there. Your program looks pretty good. However, no one is able to legally make their own modifications and share them without you stating a license.

Solution:
Make a new file called "LICENSE" in the repo. GitHub provides a templates button when you enter the editor for that. I'd recommend the MIT license for what you are doing here, but any open source license works.

**Comment by snori74** [comment]
Thanks for pointing that out! Now done.

**Comment by snori74** [comment]
and closed.
